Repository woowa-techcamp-2022/web-todo-7, pull requests merged in 2022-07, with the labels that each got.

#4 Feat/Setup MySQL
  package-lock.json
  package.json
  src/app.js
  src/config/constant.js
  src/db/index.js
  src/index.js
Labels: feature

#12 feat: 추상화 컴포넌트 생성
  public/js/components/component.js
Labels: feature, frontend

#14 [Feature] Webpack Svg 설정 및 CSS 디렉토리 구조 변경
  package-lock.json
  package.json
  public/css/normalize.css
  public/css/styles.css
  public/images/close.svg
  public/images/menu.svg
  public/images/plus.svg
  public/styles/styles.css
  webpack.config.js
Labels: feature, frontend

#19 [Feature] 헤더 관련 기능 구현
  public/js/components/Header/index.js
  public/js/components/Header/style.css
  public/js/components/LogItem/index.js
  public/js/components/LogItem/style.css
  public/js/components/LogList/index.js
  public/js/components/LogList/style.css
  public/js/components/Sidebar/index.js
  public/js/components/Sidebar/style.css
  public/js/utils/date.js
Labels: feature, frontend

#18 [Feature] MainContent Component 생성
  public/css/normalize.css
  public/css/styles.css
  public/images/close.svg
  public/images/menu.svg
  public/images/plus.svg
  public/js/app.js
  public/js/components/MainContent/index.js
  public/js/components/MainContent/style.css
  public/js/components/TodoItem/index.js
  public/js/components/TodoItem/style.css
  public/js/components/TodoSection/SectionHeader.js
  public/js/components/TodoSection/SectionList.js
  public/js/components/TodoSection/index.js
  public/js/components/TodoSection/style.css
  public/js/components/component.js
  public/js/index.js
Labels: feature, frontend

#25 [Feature] TodoList Style 구현 및 drag and drop 구현
  public/css/styles.css
  public/js/app.js
  public/js/components/MainContent/index.js
  public/js/components/TodoItem/BaseItem.js
  public/js/components/TodoItem/InputItem.js
  public/js/components/TodoItem/index.js
  public/js/components/TodoItem/style.css
  public/js/components/TodoSection/SectionHeader.js
  public/js/components/TodoSection/SectionList.js
  public/js/components/TodoSection/index.js
  public/js/components/TodoSection/style.css
  public/js/components/component.js
  public/js/lib/isBeforeCurrentElement.js
Labels: feature, frontend

#23 [Feature] Todo 관련 API 기능 추가
  src/app.js
  src/controllers/todoController.js
  src/routes/apiRouter.js
  src/routes/todoRouter.js
  src/services/todoService.js
Labels: feature, backend

#29 [Feature] Modal 생성 및 이벤트 등록
  public/index.html
  public/js/app.js
  public/js/components/Modal/index.js
  public/js/components/Modal/style.css
  public/js/components/TodoItem/style.css
  public/js/components/TodoSection/index.js
  public/js/lib/customEvent.js
Labels: feature, frontend

#33 [Feature] todo API 관련 로직 작성
  public/js/api/index.js
  public/js/api/log.js
  public/js/api/section.js
  public/js/api/todo.js
  public/js/app.js
  public/js/components/MainContent/index.js
  public/js/components/Modal/index.js
  public/js/components/TodoItem/InputItem.js
  public/js/components/TodoItem/style.css
  public/js/components/TodoSection/SectionList.js
  public/js/components/TodoSection/index.js
  src/services/todoService.js
Labels: feature, frontend

#35 [fix] Database Query 형식 변경
  src/controllers/logController.js
  src/controllers/sectionController.js
  src/controllers/todoController.js
  src/services/logService.js
  src/services/sectionService.js
  src/services/todoService.js
Labels: backend, fix

#39 [Feature] Sidebar 및 TodoSection 관련 기능 추가
  package-lock.json
  package.json
  public/css/styles.css
  public/images/create.png
  public/images/delete.png
  public/images/move.png
  public/images/update.png
  public/js/components/LogItem/index.js
  public/js/components/LogItem/style.css
  public/js/components/LogList/style.css
  public/js/components/MainContent/style.css
  public/js/components/Sidebar/style.css
  public/js/components/TodoSection/style.css
  webpack.config.js
Labels: feature, frontend
